'use client';

import { useEffect, useState } from 'react';
import { getActivityLogs, type ActivityFilters } from '@/app/actions/vehicles';

type Result=Awaited<ReturnType<typeof getActivityLogs>>;
const fmt=(n:number)=>n.toLocaleString('ar-EG');
const sectionLabels:Record<string,string>={users:'المستخدمون',permissions:'الصلاحيات',properties:'العقارات',cars:'السيارات',bookings:'الحجوزات',settings:'الإعدادات'};
const actionLabels:Record<string,string>={create:'إنشاء',update:'تعديل',delete:'حذف',archive:'أرشفة',deactivate:'تعطيل',activate:'تفعيل',cancel:'إلغاء',status_change:'تغيير الحالة',permission_update:'تعديل الصلاحيات'};
export function ActivityLogManager(){
 const [filters,setFilters]=useState<ActivityFilters>({page:1});const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Result['rows'][number]|null>(null);
 useEffect(()=>{let live=true;getActivityLogs(filters).then(data=>{if(live){setResult(data);setError('');}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'تعذر تحميل السجل.');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[filters]);
 function update(key:keyof ActivityFilters,value:string|boolean|number){setFilters(old=>({...old,[key]:value,page:key==='page'?Number(value):1}));}
 const summary=result?.summary;
 return <main className="dashboard-content space-y-5" dir="rtl"><section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[['إجمالي العمليات',summary?.total],['ناجحة',summary?.success],['فاشلة أو مرفوضة',summary?.failed],['مستخدمون نشطون',summary?.users],['عمليات حساسة',summary?.sensitive]].map(([label,value])=><article key={String(label)} className="panel rounded-2xl p-4"><p className="text-xs text-[var(--muted)]">{label}</p><strong className="mt-2 block text-2xl">{value===undefined?'—':fmt(Number(value))}</strong></article>)}</section>
 <section className="panel grid gap-3 rounded-2xl p-4 sm:grid-cols-2 lg:grid-cols-4"><input onChange={e=>update('search',e.target.value)} placeholder="بحث بالاسم أو البريد أو المعرّف" className="rounded-xl border border-[var(--line)] bg-transparent p-3"/><select onChange={e=>update('section',e.target.value)} className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3"><option value="">كل الأقسام</option>{['users','permissions','properties','cars','bookings','settings'].map(x=><option key={x} value={x}>{sectionLabels[x]??'قسم آخر'}</option>)}</select><select onChange={e=>update('outcome',e.target.value)} className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3"><option value="">كل النتائج</option><option value="success">ناجحة</option><option value="failure">فاشلة</option><option value="denied">مرفوضة</option></select><label className="flex items-center gap-2 rounded-xl border border-[var(--line)] p-3"><input type="checkbox" onChange={e=>update('sensitive',e.target.checked)}/>العمليات الحساسة فقط</label><label className="text-xs">من<input type="date" onChange={e=>update('since',e.target.value?new Date(`${e.target.value}T00:00:00+02:00`).toISOString():'')} className="mt-1 block w-full rounded-lg border border-[var(--line)] bg-transparent p-2"/></label><label className="text-xs">إلى<input type="date" onChange={e=>update('until',e.target.value?new Date(`${e.target.value}T23:59:59+02:00`).toISOString():'')} className="mt-1 block w-full rounded-lg border border-[var(--line)] bg-transparent p-2"/></label></section>
 <div className="flex flex-wrap gap-2"><button onClick={()=>{const d=new Date();d.setHours(0,0,0,0);setFilters(old=>({...old,since:d.toISOString(),until:undefined,page:1}));}} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs">اليوم</button><button onClick={()=>{const d=new Date();d.setDate(d.getDate()-7);setFilters(old=>({...old,since:d.toISOString(),until:undefined,page:1}));}} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs">آخر 7 أيام</button><button onClick={()=>{const d=new Date();d.setDate(d.getDate()-30);setFilters(old=>({...old,since:d.toISOString(),until:undefined,page:1}));}} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs">آخر 30 يومًا</button><button onClick={()=>setFilters(old=>({...old,since:undefined,until:undefined,page:1}))} className="rounded-lg border border-[var(--line)] px-3 py-2 text-xs">كل الفترات</button></div>
 {error&&<p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
 <section className="panel overflow-x-auto rounded-2xl p-4"><table className="w-full min-w-[900px] text-right text-sm"><thead><tr className="border-b border-[var(--line)] text-[var(--muted)]">{['التاريخ والوقت','المستخدم','القسم','العملية','العنصر','الوصف','النتيجة',''].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{result?.rows.map(row=><tr key={row.id} className="border-b border-[var(--line)]"><td className="p-3">{new Date(row.created_at).toLocaleString('ar-EG',{timeZone:'Africa/Cairo'})}</td><td className="p-3">{row.actor_name||'مستخدم غير متاح'}<small dir="ltr" className="block text-[var(--muted)]">{row.actor_id}</small></td><td className="p-3">{sectionLabels[row.section]??'قسم آخر'}</td><td className="p-3">{actionLabels[row.action]??'عملية أخرى'}</td><td className="p-3">{row.entity_label||row.entity_id||'—'}</td><td className="p-3">{row.description}</td><td className="p-3">{row.outcome==='success'?'ناجحة':row.outcome==='denied'?'مرفوضة':'فاشلة'}</td><td className="p-3"><button onClick={()=>setSelected(row)} className="font-bold text-[var(--brand)]">التفاصيل</button></td></tr>)}</tbody></table>{loading&&<p className="p-5 text-center text-sm text-[var(--muted)]">جارٍ التحميل…</p>}{!loading&&result?.rows.length===0&&<p className="p-8 text-center">لا توجد عمليات تطابق التصفية.</p>}</section>
 <div className="flex items-center justify-between"><button disabled={!result||result.page<=1} onClick={()=>update('page',(result?.page??1)-1)} className="rounded-xl border border-[var(--line)] px-4 py-2 disabled:opacity-40">السابق</button><span className="text-sm">صفحة {fmt(result?.page??1)} من {fmt(result?.pages??1)}</span><button disabled={!result||result.page>=result.pages} onClick={()=>update('page',(result?.page??1)+1)} className="rounded-xl border border-[var(--line)] px-4 py-2 disabled:opacity-40">التالي</button></div>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><section className="w-full max-w-xl rounded-2xl bg-[var(--surface)] p-6"><h2 className="text-lg font-black">تفاصيل العملية</h2><p className="mt-3">{selected.description}</p><pre className="mt-4 max-h-72 overflow-auto rounded-xl bg-[var(--canvas)] p-4 text-xs" dir="ltr">{JSON.stringify(selected.details,null,2)}</pre><button onClick={()=>setSelected(null)} className="mt-4 rounded-xl border border-[var(--line)] px-4 py-2">إغلاق</button></section></div>}
 </main>;
}
