'use client';
import { LoaderCircle, Save } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
type Settings = { id: string; app_name: string | null; contact_phone: string | null; about_text: string | null };
export function SettingsForm() { const [settings, setSettings] = useState<Settings | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
 const load = useCallback(async () => { const { data, error } = await createClient().from('app_settings').select('id,app_name,contact_phone,about_text').limit(1).maybeSingle(); if (error) setMessage('تعذر تحميل إعدادات المنصة.'); else setSettings(data as Settings | null); setLoading(false); }, []);
 useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
 async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!settings) return; setSaving(true); const { error } = await createClient().from('app_settings').update({ app_name: settings.app_name?.trim() || 'القِرش | Alqirsh', contact_phone: settings.contact_phone?.trim() || '01090886364 / 01019905309', about_text: settings.about_text?.trim() || null }).eq('id', settings.id); setMessage(error ? 'تعذر حفظ الإعدادات. تحقق من الصلاحيات.' : 'تم حفظ إعدادات المنصة بنجاح.'); setSaving(false); }
 if (loading) return <main className="grid min-h-64 place-items-center p-5"><LoaderCircle className="animate-spin text-[var(--brand)]"/></main>;
 if (!settings) return <main className="p-5 lg:p-9"><section className="panel rounded-2xl p-6"><h2 className="font-black">لا توجد إعدادات قابلة للتعديل</h2><p className="mt-2 text-sm text-[var(--muted)]">أنشئ سجل الإعدادات في قاعدة البيانات أولاً؛ لا تنشئ الواجهة بيانات وهمية تلقائياً.</p></section></main>;
 return <form onSubmit={save} className="max-w-3xl p-5 lg:p-9"><section className="panel rounded-2xl p-6"><p className="eyebrow">بيانات المنصة</p><h2 className="mt-1 text-xl font-black">إعدادات الشركة والتواصل</h2><div className="mt-6 grid gap-5"><label className="text-sm font-bold">اسم المنصة<input value={settings.app_name ?? ''} onChange={(event) => setSettings({ ...settings, app_name: event.target.value })} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent p-3 outline-none focus:ring-2 focus:ring-emerald-500"/></label><label className="text-sm font-bold">هاتف التواصل<input dir="ltr" value={settings.contact_phone ?? ''} onChange={(event) => setSettings({ ...settings, contact_phone: event.target.value })} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent p-3 text-right outline-none focus:ring-2 focus:ring-emerald-500"/></label><label className="text-sm font-bold">نبذة عن المنصة<textarea value={settings.about_text ?? ''} onChange={(event) => setSettings({ ...settings, about_text: event.target.value })} rows={5} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent p-3 outline-none focus:ring-2 focus:ring-emerald-500"/></label></div><button disabled={saving} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[var(--brand)] px-5 font-bold text-white disabled:opacity-60"><Save size={18}/>{saving ? 'جارٍ الحفظ…' : 'حفظ الإعدادات'}</button>{message && <p role="status" className="mt-4 text-sm font-semibold text-[var(--muted)]">{message}</p>}</section></form>; }
