'use client';

import { useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import { CalendarPlus, X } from 'lucide-react';
import { createVehicleBooking, getVehiclePermissionSnapshot } from '@/app/actions/vehicles';

export function VehicleBookingButton({ vehicle }: { vehicle: { id:string;title:string;brand:string|null;model:string|null;image_url:string|null;daily_price:number|null;weekly_price:number|null;monthly_price:number|null } }) {
  const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const [allowed,setAllowed]=useState(false);
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [deposit,setDeposit]=useState('0'); const [notes,setNotes]=useState('');
  const daily=vehicle.daily_price ?? (vehicle.weekly_price ? vehicle.weekly_price/7 : vehicle.monthly_price ? vehicle.monthly_price/30 : 0);
  const amount=useMemo(()=>{if(!start||!end)return 0;const hours=(new Date(end).getTime()-new Date(start).getTime())/3600000;return hours>0?Math.ceil(hours/24)*daily:0;},[start,end,daily]);
  useEffect(()=>{let active=true;void getVehiclePermissionSnapshot().then((permissions)=>{if(active)setAllowed(permissions?.canCreateBookings===true);});return()=>{active=false;};},[]);
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setMessage('');try{await createVehicleBooking({vehicleId:vehicle.id,customerName:name,customerPhone:phone,startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),deposit:Number(deposit),notes});setOpen(false);setName('');setPhone('');setStart('');setEnd('');setDeposit('0');setNotes('');}catch(error){setMessage(error instanceof Error && (error.message.includes('صلاحية')||error.message.includes('محجوز')||error.message.includes('تاريخ'))?error.message:'تعذر حفظ الحجز. يرجى مراجعة البيانات والمحاولة مرة أخرى.');}finally{setSaving(false);}}
  return <>{allowed&&<button type="button" onClick={()=>setOpen(true)} className="rounded-xl bg-[var(--brand)] px-3 py-2 text-sm font-bold text-white"><CalendarPlus size={15} className="ml-1 inline"/>إضافة حجز</button>}{open&&<div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto bg-black/55 p-3"><form onSubmit={submit} className="my-auto w-full max-w-lg rounded-2xl bg-[var(--surface)] p-5" dir="rtl"><div className="flex items-start justify-between"><div><p className="text-xs text-[var(--muted)]">حجز سيارة</p><h2 className="mt-1 text-xl font-black">{vehicle.title}</h2><p className="text-sm">{vehicle.brand} {vehicle.model}</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="إغلاق" className="rounded-lg border border-[var(--line)] p-2"><X size={18}/></button></div>{vehicle.image_url&&<div className="relative mt-4 h-40 w-full overflow-hidden rounded-xl"><Image src={vehicle.image_url} alt={vehicle.title} fill sizes="(max-width: 640px) 100vw, 512px" className="object-cover"/></div>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم العميل" className="rounded-xl border border-[var(--line)] bg-transparent p-3"/><input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الهاتف" className="rounded-xl border border-[var(--line)] bg-transparent p-3"/><label className="text-sm">موعد الاستلام<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--line)] bg-transparent p-3"/></label><label className="text-sm">موعد الإعادة<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--line)] bg-transparent p-3"/></label><label className="text-sm">العربون<input min="0" type="number" step="0.01" value={deposit} onChange={e=>setDeposit(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--line)] bg-transparent p-3"/></label><div className="rounded-xl bg-[var(--canvas)] p-3 text-sm"><p>السعر اليومي: {daily.toLocaleString('ar-EG')} ج.م</p><p>الإجمالي التقديري: {amount.toLocaleString('ar-EG')} ج.م</p><p>المتبقي: {Math.max(0,amount-Number(deposit)).toLocaleString('ar-EG')} ج.م</p></div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات" rows={2} className="mt-3 w-full rounded-xl border border-[var(--line)] bg-transparent p-3"/>{message&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-[var(--line)] px-4 py-2">إلغاء</button><button disabled={saving} className="rounded-xl bg-[var(--brand)] px-4 py-2 font-bold text-white disabled:opacity-50">{saving?'جارٍ الحفظ…':'حفظ الحجز'}</button></div></form></div>}</>;
}
